version: '3.5'

services:
  api:
    container_name: anagram-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true